### ISSUE TITLE
Fix show damage on xp drop while fishing

### ISSUE THREAD

**Issue by james-munson** [runelite-extended/runelite#122] opened 2019-04-25 23:34 UTC
Fix show damage on xp drop while fishing, it shows when you get xp from getting a fish.

**Comment by Kyleeld** [comment] 2019-04-26 10:37
LOL!!!!!!!

bit of a tricky one this... #15 the following was added to the XP drops: "Adds show what you hit next to the XP drop above enemies head"

now, by design, this should work, and you shouldn't get this issue, however, the fishing spot isn't counted as a resource and is actually counted as an NPC, therefore it counts as interacting with an NPC and gives you a fake XP drop.

we may need to add in FishingSpot.java & MinnowSpot.java from the fishing plugins so that if the npcid is in them files, it doesnt drop an XP drop.

**Comment by Kyleeld** [comment] 2019-04-26 11:31
fixed in #133

**Closed by Kyleeld** 2019-04-26 11:31 UTC
