### ISSUE TITLE
Entity Hider: Client crashed when turning the Entity Hider plugin on. 

### ISSUE THREAD

**Issue by GeChallengeM** [runelite-extended/runelite#984] opened 2019-07-11 17:50 UTC
**Describe the bug**
Client crashed when turning the Entity Hider plugin on. 

**To Reproduce**
Not sure, restarting the client seemed to fix it?

**Expected behavior**
No client crash.

**Screenshots**
Just a frozen screen.

**Environment:**
 - OS: Windows
 - RuneLite/launcher version: updated and compiled it earlier today, not sure where I can see the version number.

**Additional context**
[Selected options before turning the plugin on](https://i.imgur.com/kS4pUB9.png)
Error log:
```2019-07-11 19:30:48 [pool-2-thread-1] DEBUG n.r.client.config.ConfigManager - Setting configuration value for runelite.entityhiderplugin to true
2019-07-11 19:30:48 [pool-2-thread-1] DEBUG n.r.client.plugins.PluginManager - Plugin EntityHiderPlugin is now running
2019-07-11 19:30:48 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
java.lang.NullPointerException: null
	at em.shouldDraw(em.java:157)
	at em.j(em.java:88)
	at em.a(em.java:292)
	at fh.gy(fh.java:5052)
	at ad.gf(ad.java:4754)
	at az.ir(az.java:9676)
	at bv.iz(bv.java:9565)
	at client.gs(client.java:4587)
	at client.ab(client.java:1690)
	at ba.ar(ba.java:419)
	at ba.run(ba.java:373)
	at java.lang.Thread.run(Thread.java:748)
error_game_crash```

**Comment by Kyleeld** [comment] 2019-07-14 00:38
cant reproduce. will close this for now, if it re-occurs we can re-open.

**Closed by Kyleeld** 2019-07-14 00:38 UTC
