### ISSUE TITLE
Plugin font resets to "Regular".

### ISSUE THREAD

**Issue by m00fin** [runelite-extended/runelite#1010] opened 2019-07-16 12:12 UTC
I will set the font size to small or bold in the Runelite plugin settings, after relogging the font size of the plugins will reset to regular but the settings in the Runelite plugin will continue to say small.

**Comment by bigmemes420** [comment] 2019-07-16 12:27
Dupe of #946

**Comment by f0rmatme** [comment] 2019-07-20 22:49
https://github.com/runelite-extended/runelite/pull/1070

**Closed by f0rmatme** 2019-07-20 22:49 UTC
Labels: bug
