### ISSUE TITLE
Alchemical Hydra plugin bugged.

### ISSUE THREAD

**Issue by Aer3x** [runelite-extended/runelite#399] opened 2019-05-26 20:19 UTC
hydra plugin is kinda bugged, after first poison phase the counter keeps counting negative
(Screenshot 1)

as you can see  it keeps counting down (Screenshot 2)

At the last phase it shows the opposite prayers (Screenshot 3)
on this last screenshot you can see the range attack in the blue square.

[https://imgur.com/a/mauYIIN](https://imgur.com/a/mauYIIN)

**Comment by Ganom** [comment] 2019-05-26 21:21
Can you turn on projectiles in dev tools and see if projectiles are being properly grabbed?

**Comment by ReeeMan** [comment] 2019-05-26 22:18
Projectiles are fine. The problem is down to the Animations. The hydras death animations are still filtered. so the OnAnimationChanged is not picking up the hydra death and changing phase.

**Comment by 84lemmings** [comment] 2019-05-28 01:49
the plugin does not seem to recognize the blue hydra special attack happening, or 4th phase starting

**Comment by Lucwousin** [comment] 2019-05-29 08:21
Would be closed by #434

**Closed** 2019-05-29 08:25 UTC
Labels: bug
