### ISSUE TITLE
Current Injector Client Errors

### ISSUE THREAD

**Issue by Ganom** [runelite-extended/runelite#517] opened 2019-06-07 01:20 UTC
Place any injector errors here.

**Comment by Ganom** [comment] 2019-06-07 01:20
```2019-06-06 21:19:19 [Plugin Watcher] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.NoClassDefFoundError: Lnet/runelite/api/Client;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at com.google.inject.spi.InjectionPoint.getDeclaredFields(InjectionPoint.java:760)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:670)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:378)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:397)
	at com.google.inject.internal.BindingBuilder.toInstance(BindingBuilder.java:89)
	at net.runelite.client.plugins.PluginManager.lambda$instantiate$7(PluginManager.java:443)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:237)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:242)
	at net.runelite.client.plugins.PluginManager.instantiate(PluginManager.java:455)
	at net.runelite.client.plugins.PluginManager.scanAndInstantiate(PluginManager.java:296)
	at net.runelite.client.plugins.PluginWatcher.load(PluginWatcher.java:191)
	at net.runelite.client.plugins.PluginWatcher.scan(PluginWatcher.java:159)
	at net.runelite.client.plugins.PluginWatcher.run(PluginWatcher.java:89)
Caused by: java.lang.ClassNotFoundException: net.runelite.api.Client
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.runelite.client.plugins.PluginClassLoader.loadClass(PluginClassLoader.java:64)
	... 20 common frames omitted

**Comment by Ganom** [comment] 2019-06-07 01:21
```2019-06-06 21:20:48 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.ClassCastException: [Lrs.api.RSWidget; cannot be cast to [Lho;
	at ho.setChildren(ho.java)
	at ho.createChild(ho.java:537)
	at net.runelite.client.plugins.clanchat.ClanChatPlugin.loadClanChats(ClanChatPlugin.java:576)
	at net.runelite.client.plugins.clanchat.ClanChatPlugin.onGameTick(ClanChatPlugin.java:283)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:155)
	at client.methodDraw(client.java:1340)
	at client.ab(client.java)
	at ba.ar(ba.java:419)
	at ba.run(ba.java:373)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Ganom** [comment] 2019-06-07 01:21
```2019-06-06 21:20:52 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.NoSuchMethodError: km.remove(Lapi/Nameable;)V
	at km.p(km.java)
	at kv.a(kv.java:92)
	at client.hg(client.java:6487)
	at client.fx(client.java:3324)
	at client.al(client.java:1621)
	at ba.av(ba.java:393)
	at ba.run(ba.java:372)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Lucwousin** [comment] 2019-06-08 23:30
Current not-implemented features:

2010 menu
Renderself toggle

**Comment by Lucwousin** [comment] 2019-06-08 23:31
Inventory drag overlay NPE's if the inv slots up to the item you're dragging aren't filled

**Comment by Lucwousin** [comment] 2019-06-09 23:11
Something weird going on when zooming in/out on worldmap

**Comment by SRLJustin** [comment] 2019-06-10 03:41
2019-06-10 13:35:39 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.NoClassDefFoundError: net/runelite/client/plugins/implings/ImplingsPlugin$1
	at net.runelite.client.plugins.implings.ImplingsPlugin.npcToColor(ImplingsPlugin.java:186)
	at net.runelite.client.plugins.implings.ImplingsOverlay.render(ImplingsOverlay.java:78)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:461)
	at net.runelite.client.ui.overlay.OverlayRenderer.render(OverlayRenderer.java:227)
	at net.runelite.client.callback.Hooks.drawScene(Hooks.java:414)
	at em.az(em.java:295)
	at ad.gf(ad.java:4903)
	at az.ir(az.java:9676)
	at bv.iz(bv.java:9565)
	at client.gs(client.java:4587)
	at client.ab(client.java:1690)
	at ba.ar(ba.java:419)
	at ba.run(ba.java:373)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.runelite.client.plugins.implings.ImplingsPlugin$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 common frames omitted

From memory my client hard-crashed

**Comment by Lucwousin** [comment] 2019-06-10 15:08
@SRLJustin That has to be something both unrelated and very weird, as implingsplugin doesn't have any inner classes. I haven't gotten anything like that either

**Comment by SRLJustin** [comment] 2019-06-11 01:17
@Lucwousin Understandable, I only reported the issue because I've never had it crash with Vanilla or pre-migration, might've been a once-off, I was speaking with Null on discord and because I've been using the github build I wasn't aware I had to pass the local-injected argument to the client, this crash could be related

**Comment by Lucwousin** [comment] 2019-06-14 16:11
I think we've pretty much got all of these now, closing!

**Closed by Lucwousin** 2019-06-14 16:11 UTC
