### ISSUE TITLE
Menu entry swapper producing error & breaking menus ingame

### ISSUE THREAD

**Issue by lordzuku** [runelite-extended/runelite#1415] opened 2019-08-21 17:22 UTC
Menu entry swapper seems to randomly break, breaking left clicks on most objects / stuff requring a restart

unsure exactly what caused it but the logs showed a few errors

a few hours before it happened, noticed an oob error with the menu entrys
https://pastebin.com/vpjinKSW

then this was the logs at the time when the all menu entrys broke
https://pastebin.com/gmGbE5w6

**Comment by ThatGamerBlue** [comment] 2019-08-21 17:24
Duplicate of #1410, but I'm adding your logs over there as well because they're better.

**Closed by ThatGamerBlue** 2019-08-21 17:24 UTC
Labels: bug, duplicate
